##this function will return a list of function to
## 1.set the value of the matrix
## 2.get the value of the matrix
## 3.set the value of the inverse
## 4.get the value of the inverse

makeCacheMatrix <- function(x = matrix()) {
  inverse<-NULL
  set<-function(y){
    x<<-y
  }
  get<-function() x
  setInverse<-function(inv) inverse<<-inv

  getInverse<-function() inverse
  
  list(set = set, get = get, setInverse= setInverse, getInverse=getInverse)
}


## This function will take list generated by above function and will check
## for inverse in cache else will calculate and set inverse

cacheSolve <- function(x, ...) {
        inverse<-x$getInverse()
        if(!is.null(inverse)){
          message("getting inverse from cache")
          return(inverse)
        }
        matrix<- x$get()
        inverse<-solve(matrix)
        x$setInverse(inverse)
        inverse
}
